FROM node:lts-alpine3.24 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

FROM gcr.io/distroless/nodejs26-debian13

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules

COPY server.js ./

COPY package.json ./

USER 65532

EXPOSE 3000

CMD ["node", "server.js"]
