FROM node:lts-alpine3.24 AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

FROM node:lts-alpine3.24 

WORKDIR /app

COPY --from=build /app/node_modules ./node_modules

COPY server.js ./

COPY package.json ./

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

USER appuser 

EXPOSE 3000

CMD ["node", "server.js"]
